# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Houchen Li Field"
email: "houchen_li@hotmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  Houchen Li is a software developer of China, who earned a bachelor and a master degree in
  theoretical/computational physics. After many years trials in academia, he decided to switch to
  industry. Now, he is working as a software engineer in a company in China. He is interested in
  math, physics and computer science. This website is used to record his thoughts and experiences.
twitter_username: houchen_li
github_username: houchen-li
minimal_mistakes_skin: neon
search: true
locale: "zh-CN"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Shanghai

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Houchen Li"
  avatar : "/assets/images/Houchen_Li_CPFS.jpg"
  bio    : "Houchen Li is a software developer of China who is interested in math, physics and computer science."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://houchen-li.github.io/"
    - label: "X"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/houchen_li/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/houchen-li/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/houchen_li/"

footer:
  links:
    - label: "X"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/houchen_li/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/houchen-li/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/houchen_li/"

defaults:
  # _pages
  - scope:
      path: ""
      type: about
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
